// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import { Avatar, Dropdown, Spin } from 'antd';
import { LogoutOutlined } from '@ant-design/icons';
import { useNavigate, useModel } from 'umi';
import { user, login } from '../../api';

export const getRightRenderContent: React.FC = () => {
  const { initialState, loading, error, refresh, setInitialState } = useModel('@@initialState');
  const navigate = useNavigate();
  const avatar = (
    <span className="umi-plugin-layout-action">
        <Avatar
          size="small"
          className="umi-plugin-layout-avatar"
          src={
            initialState?.avatar ||
            'https://gw.alipayobjects.com/zos/antfincdn/XAosXuNZyF/BiazfanxmamNRoxxVxka.png'
          }
          alt="avatar"
        />
        <span className="umi-plugin-layout-name">{initialState?.name}</span>
      </span>
  );

  if (loading) {
    return (
      <div className="umi-plugin-layout-right">
        <Spin size="small" style={ { marginLeft: 8, marginRight: 8 } } />
      </div>
    );
  }

  const langMenu = {
    className: "umi-plugin-layout-menu",
    selectedKeys: [],
    items: [
      {
        key: "logout",
        label: (
          <>
            <LogoutOutlined />
            退出登录
          </>
        ),
        onClick: async () => {
          await login.exit()
          navigate('/login', { replace: true });
        },
      },
    ],
  };
  // antd@5 和  4.24 之后推荐使用 menu，性能更好
  const dropdownProps = { menu: langMenu }

  return (
    <div className="umi-plugin-layout-right anticon">
      <a href="https://note.youdao.com/s/UyNFz87q" target="_blank" rel="noreferrer">
        文档说明
      </a>
      {initialState?.name ? (
        <Dropdown {...dropdownProps} overlayClassName="umi-plugin-layout-container">
          {avatar}
        </Dropdown>
      ) : (
        avatar
      )}
    </div>
  );
}
